# Generated by Django 3.2.9 on 2021-11-23 16:17

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id',
                 models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False,
                                  unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
